---
language: python
python: 2.7
sudo: required
services:
  - docker

matrix:
  allow_failures:
  # The build is currently failing to download oracle-java8-installer
  - env: REPO=rOMERO-gateway STAGE=lib

env:
- REPO=minimal-omero-client STAGE=lib
- REPO=omero-cli-duplicate STAGE=cli
- REPO=omero-cli-render STAGE=cli
- REPO=omero-figure STAGE=app
- REPO=omero-fpbioimage STAGE=app
- REPO=omero-gallery STAGE=app
- REPO=omero-iviewer STAGE=app
- REPO=omero-mapr STAGE=app
- REPO=omero-metadata STAGE=cli PLUGIN=metadata
- REPO=omero-parade STAGE=app
- REPO=omero-prometheus-tools STAGE=lib
- REPO=omero-upload STAGE=cli
- REPO=omero-weberror STAGE=app
- REPO=omero-webtest STAGE=app
- REPO=rOMERO-gateway STAGE=lib
- REPO=scripts STAGE=scripts

script:
- cd $REPO && ln -s ../omero-test-infra .omero && .omero/docker $STAGE

