---
language: python
sudo: required

services:
  - docker

env:
- REPO=omero-iviewer STAGE=app


script:
- cd $REPO && ln -s ../omero-test-infra .omero && .omero/docker $STAGE

matrix:
  allow_failures:
    - REPO=omero-prometheus-tools STAGE=lib
    # FIXME: still on python 2
